services:
  backend:
    environment:
      - NODE_ENV=production
    command: npm start
    volumes: [] # Do not mount source in prod

  frontend:
    # Build stage will produce Nginx image
    volumes: [] # Do not mount source in prod
    stdin_open: false
    tty: false
